global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'garfana45@gmail.com'
  smtp_auth_username: 'garfana45@gmail.com'
  smtp_auth_password: 'mghj yyjl ffwh mnyn'
  smtp_require_tls: true

route:
  receiver: email-alerts
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h

receivers:
- name: email-alerts
  email_configs:
  - to: 'shravani.konnur@gmail.com'
    send_resolved: true
